import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="mt-24 border-t border-line/70 bg-ivory">
      <div className="mx-auto max-w-5xl px-6 py-12">
        <div className="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-xs">
            <p className="font-serif text-lg text-ink">
              Parent<span className="text-clay">Presents</span>
            </p>
            <p className="mt-3 text-sm leading-relaxed text-muted">
              Gift ideas for the people who raised you — chosen for meaning,
              not margin.
            </p>
          </div>

          <nav aria-label="Footer">
            <ul className="flex flex-col gap-3 text-sm text-muted">
              <li>
                <Link href="/guides" className="transition-colors hover:text-ink">
                  Gift guides
                </Link>
              </li>
              <li>
                <Link href="/#why" className="transition-colors hover:text-ink">
                  Why we exist
                </Link>
              </li>
              <li>
                <Link href="/#how" className="transition-colors hover:text-ink">
                  How we pick
                </Link>
              </li>
            </ul>
          </nav>
        </div>

        <p className="mt-10 border-t border-line/70 pt-6 text-xs text-muted">
          © {new Date().getFullYear()} ParentPresents. Ideas are reviewed by
          people, not generated by volume.
        </p>
      </div>
    </footer>
  );
}
